export const conditions = <div>
    <h1><strong>Conditions of Use</strong></h1>
    <p>&nbsp;</p>
    <p>Please read these conditions carefully before using this&nbsp;website. By using the&nbsp;BrownBoxIndia.store website, you signify your agreement to be bound by these conditions.</p>
    <p>These "Conditions of Use" constitute an electronic record within the meaning of the applicable law. This electronic record is generated by a computer system and does not require any physical or digital signatures.</p>
    <ul>
        <li>Conditions Relating to Your Use of store</li>
        <li>Notice and Procedure for Making Claims of Infringement</li>
        <li>Notice and Procedure for Notifying store of Objectionable Content</li>
    </ul>
    <p>&nbsp;</p>
    <h2><strong><strong>Conditions Relating to Your Use of </strong></strong><strong><strong>brownboxindia.store</strong></strong></h2>
    <p>&nbsp;</p>
    <ol>
        <li><strong><strong> Your Account</strong></strong></li>
    </ol>
    <p>If you use the website, you are responsible for maintaining the confidentiality of your account and password and for restricting access to your computer to prevent unauthorized access to your account. You agree to accept responsibility for all activities that occur under your account or password. You should take all necessary steps to ensure that the password is kept confidential and secure and should inform us immediately if you have any reason to believe that your password has become known to anyone else, or if the password is being, or is likely to be, used in an unauthorized manner. Please ensure that the details you provide us with are correct and complete and inform us immediately of any changes to the information that you provided when registering. You can access and update much of the information you provided us within your account&nbsp;area of the website. You agree and acknowledge that you will use your account on the website to purchase products only for your personal use and not for business purposes.</p>
    <p>&nbsp;</p>
    <ol start="2">
        <li><strong><strong>E-Platform for Communication</strong></strong></li>
    </ol>
    <p>You agree, understand and acknowledge that the website is an online platform that enables you to purchase products listed on the website at the price indicated therein at any time from any location. You further agree and acknowledge that Brown Box is only a facilitator and is not and cannot be a party to or control in any manner any transactions on the website. Accordingly, the contract of sale of products on the website shall be a strictly bipartite contract between you and the sellers on Brown Box.</p>
    <p>&nbsp;</p>
    <ol start="3">
        <li><strong><strong>Access to </strong></strong><strong><strong>store</strong></strong></li>
    </ol>
    <p>We will do our utmost to ensure that the availability of the website will be uninterrupted and that transmissions will be error-free. However, due to the nature of the Internet, this cannot be guaranteed. Also, your access to the website may also be occasionally suspended or restricted to allow for repairs, maintenance, or the introduction of new facilities or services at any time without prior notice. We will attempt to limit the frequency and duration of any such suspension or restriction.</p>
    <p>&nbsp;</p>
    <ol start="4">
        <li><strong><strong>Your Conduct</strong></strong></li>
    </ol>
    <p>You must not use the website in any way that causes, or is likely to cause, the website or access to it to be interrupted, damaged or impaired in any way You understand that you, and not Brown Box, are responsible for all electronic communications and content sent from your computer to us and you must use the website for lawful purposes only. You must not use the website for any of the following:</p>
    <ul>
        <li>for fraudulent purposes, or in connection with a criminal offense or other unlawful activity</li>
        <li>to send, use or reuse any material that does not belong to you; or is illegal, offensive (including but not limited to material that is sexually explicit content or which promotes racism, bigotry, hatred, or physical harm), deceptive, misleading, abusive, indecent, harassing, blasphemous, defamatory, libelous, obscene, pornographic, pedophilic or menacing; ethnically objectionable, disparaging or in breach of copyright, trademark, confidentiality, privacy or any other proprietary information or right; or is otherwise injurious to third parties, or relates to or promotes money laundering or gambling; or is harmful to minors in any way; or impersonates another person; or threatens the unity, integrity, security or sovereignty of India or friendly relations with foreign States; or objectionable or otherwise unlawful in any manner whatsoever; or which consists of or contains software viruses, political campaigning, commercial solicitation, chain letters, mass mailings or any "spam</li>
        <li>to cause annoyance, inconvenience or needless anxiety</li>
    </ul>
    <p>&nbsp;</p>
    <ol start="5">
        <li><strong><strong>Copyright, authors' rights, and database rights</strong></strong></li>
    </ol>
    <p>All content included on the website, such as text, graphics, logos, button icons, images, audio clips, digital downloads, data compilations, and software, is the property of Brown Box, its affiliates, or its content suppliers and is protected by India and international copyright, authors' rights, and database right laws. The compilation of all content on this website is the exclusive property of brownboxindia.store&nbsp;and its affiliates and is protected by laws of India and international copyright and database right laws. All software used on this website is the property of brownboxindia.store, its affiliates, or its software suppliers and is protected by India and international copyright and author's rights laws.</p>
    <p>You may not systematically extract/ or re-utilize parts of the contents of the website without Brown Box&nbsp;and/or its affiliates (as may be applicable) express written consent. In particular, you may not utilize any data mining, robots, or similar data gathering and extraction tools to extract (whether once or many times) for re-utilization of any substantial parts of this website, without Brown Box&nbsp;and/or its affiliate's (as may be applicable) express written consent. You may also not create and/ or publish your own database that features substantial (eg: prices and product listings) parts of this website without Brown Box&nbsp;and / or its affiliate's (as may be applicable) express written consent.</p>
    <p>&nbsp;</p>
    <ol start="6">
        <li><strong><strong>Disclaimer</strong></strong></li>
    </ol>
    <p>You acknowledge and undertake that you are accessing the services on the website and transacting at your own risk and are using your best and prudent judgment before entering into any transactions through the website. You further acknowledge and undertake that you will use the website to order products only for your personal use and not for business purposes. We shall neither be liable nor responsible for any actions or inactions of sellers nor any breach of conditions, representations or warranties by the sellers or manufacturers of the products and hereby expressly disclaim and any all responsibility and liability in that regard. We shall not mediate or resolve any dispute or disagreement between you and the sellers or manufacturers of the products.</p>
    <p>We further expressly disclaim any warranties or representations (express or implied) in respect of quality, suitability, accuracy, reliability, completeness, timeliness, performance, safety, merchantability, fitness for a particular purpose, or legality of the products listed or displayed or transacted or the content (including product or pricing information and/or specifications) on the website. While we have taken precautions to avoid inaccuracies in content, this website, all content, information (including the price of products), software, products, services, and related graphics are provided as is, without warranty of any kind. We do not implicitly or explicitly support or endorse the sale or purchase of any products on the website. At no time shall any right, title, or interest in the products sold through or displayed on the website vest with Brown Box nor shall Brown Box have any obligations or liabilities in respect of any transactions on the website.</p>
    <p>&nbsp;</p>
    <ol start="7">
        <li><strong><strong>Children</strong></strong></li>
    </ol>
    <p>Use of brownboxindia.store&nbsp;is available only to persons who can form a legally binding contract under the Indian Contract Act, 1872. If you are a minor i.e. under the age of 18 years, you may use brownboxindia.store&nbsp;only with the involvement of a parent or guardian.</p>
    <p>&nbsp;</p>
    <ol start="8">
        <li><strong><strong>Communications</strong></strong></li>
    </ol>
    <p>When you visit BrownBoxIndia.store, you are communicating with us electronically. You will be required to provide a valid phone number while placing an order with us. We may communicate with you by e-mail, SMS, phone call or by posting notices on the website or by any other mode of communication. For contractual purposes, you consent to receive communications (including transactional, promotional and/or commercial messages), from us with respect to your use of the website and/or your order placed on the website.</p>
    <p>&nbsp;</p>
    <ol start="9">
        <li><strong><strong> Alteration of Service or Amendments to the Conditions</strong></strong></li>
    </ol>
    <p>We reserve the right to make changes to our website, policies, and these Conditions of Use at any time. You will be subject to the policies and Conditions of Use in force at the time that you use the website or that you order goods from us unless any change to those policies or these conditions is required to be made by law or government authority (in which case it will apply to orders previously placed by you). If any of these conditions is deemed invalid, void, or for any reason unenforceable, that condition will be deemed severable and will not affect the validity and enforceability of any remaining condition.</p>
    <p>&nbsp;</p>
    <ol start="10">
        <li><strong><strong>Events beyond our reasonable control</strong></strong></li>
    </ol>
    <p>We will not be held responsible for any delay or failure to comply with our obligations under these conditions if the delay or failure arises from any cause which is beyond our reasonable control. This condition does not affect your statutory rights.</p>
    <p>&nbsp;</p>
    <ol start="11">
        <li><strong><strong>Waiver</strong></strong></li>
    </ol>
    <p>If you breach these conditions and we take no action, we will still be entitled to use our rights and remedies in any other situation where you breach these conditions.</p>
    <p>&nbsp;</p>
    <ol start="12">
        <li><strong><strong>Governing law and Jurisdiction</strong></strong></li>
    </ol>
    <p>These conditions are governed by and construed in accordance with the laws of India. You agree, as we do, to submit to the exclusive jurisdiction of the courts at Delhi.</p>
    <p><strong><strong>&nbsp;</strong></strong></p>
    <ol start="13">
        <li><strong><strong>Our Details</strong></strong></li>
    </ol>
    <p>This website is operated by Brown Box.</p>
    <p>For the Brown Box&nbsp;website, you could contact us by visiting:&nbsp;<a href="https://www.amazon.in/gp/help/contact-us"><u>www.</u><u>b</u></a><u>rownboxindia.store</u></p>
    <p>&nbsp;</p>
</div>